services:
  db:
    container_name: db
    image: mongo
    # restart: always
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u root -p mongopass --quiet | grep 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
  oscarsservice:
    container_name: oscarsservice
    # restart: on-failure:5
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - 8080:8080